//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayaApp.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KayaApp.Language.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açık Hesap.
        /// </summary>
        internal static string AcikHesap {
            get {
                return ResourceManager.GetString("AcikHesap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka.
        /// </summary>
        internal static string Banka {
            get {
                return ResourceManager.GetString("Banka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgiler Yükleniyor..
        /// </summary>
        internal static string BilgiEkrani_YUKLENIYOR {
            get {
                return ResourceManager.GetString("BilgiEkrani_YUKLENIYOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string demobtn {
            get {
                return ResourceManager.GetString("demobtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veriler Yükleniyor. Lütfen bekleyiniz....
        /// </summary>
        internal static string dialog_logginginplzwait {
            get {
                return ResourceManager.GetString("dialog_logginginplzwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GİRİŞ YAP.
        /// </summary>
        internal static string loginbtn {
            get {
                return ResourceManager.GetString("loginbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FİNANS.
        /// </summary>
        internal static string MAINMENU_CHASH {
            get {
                return ResourceManager.GetString("MAINMENU_CHASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÜŞTERİLER.
        /// </summary>
        internal static string MAINMENU_CUSTOMERS {
            get {
                return ResourceManager.GetString("MAINMENU_CUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİPARİŞLER.
        /// </summary>
        internal static string MAINMENU_ORDERS {
            get {
                return ResourceManager.GetString("MAINMENU_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALIŞ FATURALARI.
        /// </summary>
        internal static string MAINMENU_PURCHASE {
            get {
                return ResourceManager.GetString("MAINMENU_PURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAPORLAR.
        /// </summary>
        internal static string MAINMENU_REPORTS {
            get {
                return ResourceManager.GetString("MAINMENU_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATIŞ FATURALARI.
        /// </summary>
        internal static string MAINMENU_SALES_INVOICE {
            get {
                return ResourceManager.GetString("MAINMENU_SALES_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOKLAR.
        /// </summary>
        internal static string MAINMENU_STOCKS {
            get {
                return ResourceManager.GetString("MAINMENU_STOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPOLAR.
        /// </summary>
        internal static string MAINMENU_WAREHOUSE {
            get {
                return ResourceManager.GetString("MAINMENU_WAREHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDV.
        /// </summary>
        internal static string MoneyTAX {
            get {
                return ResourceManager.GetString("MoneyTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÜŞTERİ ARA.
        /// </summary>
        internal static string MusteriAra {
            get {
                return ResourceManager.GetString("MusteriAra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÜŞTERİLER.
        /// </summary>
        internal static string Musteriler {
            get {
                return ResourceManager.GetString("Musteriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit.
        /// </summary>
        internal static string Nakit {
            get {
                return ResourceManager.GetString("Nakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peşin.
        /// </summary>
        internal static string Pesin {
            get {
                return ResourceManager.GetString("Pesin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK ARA.
        /// </summary>
        internal static string StokAra {
            get {
                return ResourceManager.GetString("StokAra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOKLAR.
        /// </summary>
        internal static string Stoklar {
            get {
                return ResourceManager.GetString("Stoklar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Adı.
        /// </summary>
        internal static string userscompanyname {
            get {
                return ResourceManager.GetString("userscompanyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string userspass {
            get {
                return ResourceManager.GetString("userspass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreyi Hatırla?.
        /// </summary>
        internal static string userspassremeber {
            get {
                return ResourceManager.GetString("userspassremeber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string usersusername {
            get {
                return ResourceManager.GetString("usersusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Faturası.
        /// </summary>
        internal static string xSatisFaturasi_1 {
            get {
                return ResourceManager.GetString("xSatisFaturasi_1", resourceCulture);
            }
        }
    }
}
